version: '3.9'

services:
    scylla:
        image: adminreseau01/scylla:latest
        container_name: scylla-rentacar
        ports:
            - "9045:9042"
        volumes:
            - scylla-data:/var/lib/scylla
        networks:
            - backend
        command: --smp 1 --memory 512M --overprovisioned 1 --api-address 0.0.0.0

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rentacar-api
        ports:
            - "8080:8080"
        depends_on:
            - scylla
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_CASSANDRA_CONTACT_POINTS=scylla
            - SPRING_DATA_CASSANDRA_PORT=9045
            - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=rental
            - SPRING_DATA_CASSANDRA_USERNAME=cassandra
            - SPRING_DATA_CASSANDRA_PASSWORD=cassandra
            - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
        networks:
            - backend

volumes:
    scylla-data:

networks:
    backend:
        driver: bridge
